### PR TITLE
Implement support for MyGet WebHooks

### PR DESCRIPTION
**Pull request by maartenba**
Add support for MyGet WebHooks - see http://docs.myget.org/docs/reference/webhooks

Contains a `MyGetWebHookHandlerBase` that allows consumers to work with strong-typed payloads.

### CODE REVIEW

**Comment by maartenba** [comment]
Guess that  MyGetWebHookHandlerBase  can be removed in favor of just having the objects in place?

**Comment by HenrikFrystykNielsen** [comment]
Hi @maartenba -- sorry for the delay! I'll have a look as soon as possible! The pattern we have used elsewhere is to serve up the JSON and then have helper classes that people can use if they want to. Thanks!

**Comment by maartenba** [comment]
Thanks, let me know any feedback and we'll update this.

**Comment by HenrikFrystykNielsen** [comment]
Hi @maartenba - thanks for the PR and sorry for the delay. It's committed now to dev branch with a few updates: e97a9a086ec2fa4f79326cfdb8e08e9e18d10ab7. Would you be willing to check that it looks ok?

**Comment by maartenba** [comment]
Happy with it - looks good. Thanks @HenrikFrystykNielsen !

/cc @xavierdecoster

**Pull request closed without merging**
