### PR TITLE
Fix gaps in final commit for #258 (c9ab0b4ede)

### PR DESCRIPTION
**Pull request by dougbu**
- register `DefaultWebHookMetadataProvider` in DI
- correct names of resources

### CODE REVIEW

**Comment by dougbu** [comment]
This is urgent because it prevents WebHook actions starting cleanly.

**Comment by dougbu** [comment]
@Eilon plan was to add functional tests of the sample as I work on #180. My concern is the first functional test may take enough time to bump another issue into Ask mode.

On the other hand, I have confirmed the samples now start smoothly.

Thoughts?

**Comment by dougbu** [comment]
:up::date: to fix other gaps and add first functional tests

**Comment by dougbu** [comment]
This PR addresses #275.

**Comment by WestDiscGolf** [comment]
The functional tests don't have the right target framework.

image

**Comment by dougbu** [comment]
:up::date: rebased

**Comment by dougbu** [comment]
eecaac30c5

**Pull request closed without merging**
