### PR TITLE
Added support for Zendesk

### PR DESCRIPTION
**Pull request by garora**
Local branch rebased from upstream. New ```PR``` for ```Zendesk``` webhook support for Devices.

### CODE REVIEW

**Comment by garora** [comment]
@HenrikFrystykNielsen - A fresh ```PR``` for ```Zendesk``` WebHook support (for Devices). I need atleast a beta version for this. I will appreciate your efforts/support, if you can take a this as  a next ```PR``` merge.

**Comment by garora** [comment]
@HenrikFrystykNielsen - did you get a chance to look into ```PR``` for ```Zendesk``` ?

**Comment by HenrikFrystykNielsen** [comment]
Gaurav, I can't seem to be able to get Zendesk to send a WebHook? I have registered an app with a WebHook but don't know how to get it to fire. Any ideas?

**Comment by garora** [comment]
You need to map your emailId. They have very decent documentations to refer.

**Comment by garora** [comment]
Sorry, I missed link. Here it is:
https://developer.zendesk.com/embeddables/docs/android/push_notifications_webhook

**Comment by garora** [comment]
@HenrikFrystykNielsen - just to quick check, do we have any plan for this ```PR``` ?

**Comment by HenrikFrystykNielsen** [comment]
I have been working on it for quite a while but haven't been able to get Zendesk to actually send me a webhook. For now I'll just go based on the docs.

**Comment by garora** [comment]
Thanks for your support!
I have more PR - waiting on current. In between, is there anyway to make a
new PR while first one is in process ?


On Tue, May 24, 2016 at 10:16 PM, Henrik Frystyk Nielsen <
notifications@github.com> wrote:

> I have been working on it for quite a while but haven't been able to get
> Zendesk to actually send me a webhook. For now I'll just go based on the
> docs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/WebHooks/pull/24#issuecomment-221332682>
>



-- 
Thanks & Regards,
Gaurav Arora

**Comment by HenrikFrystykNielsen** [comment]
thanks for the PR -- it's now in: 1a213d7b9c95086ed0820942abb9ff6cf1488e0e

**Comment by garora** [comment]
Thanks a ton! Now I can make other PR

**Pull request closed without merging**
