### PR TITLE
Facebook Webhooks For Messenger Bot

### PR DESCRIPTION
**Pull request by BlueCity**
Hello, 
Firstly thanks for all these webhooks apis. But nowadays i am working on facebook messenger https://developers.facebook.com/docs/messenger-platform/webhook-reference but i can't find webhooks api for Facebook. Is it possible to add it ?

### CODE REVIEW

**Comment by HenrikFrystykNielsen** [comment]
@BlueCity Hi there and thanks for your pull request -- greatly appreciated! However, I am not sure you got the PR right -- it says merging from master into rev while I would have expected merging from a branch in your clone. Suggestions?

**Comment by BlueCity** [comment]
@HenrikFrystykNielsen Hello, actually you are right, i did not pay attention when i start this PR is it possible to change it ?

**Comment by HenrikFrystykNielsen** [comment]
Whatever is simplest for you.

**Comment by BlueCity** [comment]
@HenrikFrystykNielsen Hello sir, I cant change comparing from master to master when i try to change it, Create New Pull Request button  disabled i put also screenshot below. How i can change it ? 

screenshot_4

**Comment by HenrikFrystykNielsen** [comment]
@BlueCity Sorry for the trouble. The process is to create your own repo clone, commit your changes to there, and then submit the PR. Then you will see the diffs between your edits in your repo and the bits in the main dev branch.

**Pull request merged**
